name: Build and Package EXEs

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executables
      run: |
        # Build each script without bundling resources & copy
        pyinstaller --onefile --clean gui2.py
        rm -rf dist
        rm -rf build
        rm -f gui2.spec
        pyinstaller --onefile --clean upload.py
        rm -rf dist
        rm -rf build
        rm -f upload.spec
        pyinstaller --onefile --clean download.py
        rm -rf dist
        rm -rf build
        rm -f download.spec
        pyinstaller --onefile --clean generate_thumb.py
        rm -rf dist
        rm -rf build
        rm -f generate_thumb.spec

    - name: Create Zip File
      run: |
        # Create a zip file with all contents of the dist directory
        powershell Compress-Archive -Path * -DestinationPath ./package.zip

    - name: Upload Zip File
      uses: actions/upload-artifact@v2
      with:
        name: packaged_executables
        path: package.zip
