name: Build and Package EXEs

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executables
      run: |
        # Build each script without bundling resources & copy
        pyinstaller --onefile --clean gui2.py
        cp dist/gui2.exe gui2.exe
        Remove-Item -Recurse -Force dist
        Remove-Item -Recurse -Force build
        Remove-Item -Force gui2.spec
        cd py_files
        pyinstaller --onefile --clean upload.py
        cp dist/upload.exe upload.exe
        Remove-Item -Recurse -Force dist
        Remove-Item -Recurse -Force build
        Remove-Item -Force upload.spec
        pyinstaller --onefile --clean download.py
        cp dist/download.exe download.exe
        Remove-Item -Recurse -Force dist
        Remove-Item -Recurse -Force build
        Remove-Item -Force download.spec
        pyinstaller --onefile --clean generate_thumb.py
        cp dist/generate_thumb.exe generate_thumb.exe
        Remove-Item -Recurse -Force dist
        Remove-Item -Recurse -Force build
        Remove-Item -Force generate_thumb.spec

    - name: Create Zip File
      run: |
        # Create a zip file with all contents of the dist directory
        powershell Compress-Archive -Path * -DestinationPath ./package.zip

    - name: Upload Zip File
      uses: actions/upload-artifact@v4
      with:
        name: packaged_files
        path: package.zip
